use_frameworks!

target 'ZHTableViewGroup_Example' do
  pod 'ZHTableViewGroupObjc', :path => '../ZHTableViewGroupObjc.podspec'
  pod 'Masonry'
  target 'ZHTableViewGroup_Tests' do
    inherit! :search_paths

    
  end
end
